FROM python:3.7

RUN \
  apt-get update && \
  apt-get install -yqq apt-transport-https
RUN \
  echo "deb https://deb.nodesource.com/node_8.x stretch main" > /etc/apt/sources.list.d/nodesource.list && \
  wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list && \
  wget -qO- https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  apt-get update && \
  apt-get install -yqq nodejs yarn && \
  pip install -U pip && pip install pipenv && \
  npm i -g npm@^6 && \
  rm -rf /var/lib/apt/lists/*

ENV FLASK_DEBUG 1
WORKDIR /app

ENV NPM_CONFIG_LOGLEVEL warn

COPY static /app/static
COPY webpack /app/webpack
COPY package.json /app/
COPY yarn.lock /app/
COPY .babelrc /app/
RUN yarn

COPY requirements.txt /app/
RUN pip3 install -r /app/requirements.txt
COPY dev-requirements.txt /app/
RUN pip3 install -r /app/dev-requirements.txt

COPY . /app

ENTRYPOINT /bin/bash
