FROM node:8-alpine

ENV FLASK_DEBUG 1

RUN apk add --no-cache build-base python3 python3-dev && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
    rm -r /root/.cache


WORKDIR /app

ENV NPM_CONFIG_LOGLEVEL warn

COPY static /app/static
COPY webpack /app/webpack
COPY package.json /app/
COPY yarn.lock /app/
COPY .babelrc /app/
RUN yarn

COPY requirements.txt /app/
RUN pip3 install -r /app/requirements.txt
COPY dev-requirements.txt /app/
RUN pip3 install -r /app/dev-requirements.txt

ENTRYPOINT /bin/ash
