version: '3.8'

services:

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 80:5000
    entrypoint: python -m pytest "tests" --cov=.
    environment:
      - SECRET_KEY=sk_test_ok
      - REDIS_URL="rediss://localhost:6379"
